# Generated by Django 5.0.3 on 2024-04-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_channels_subchannels_channelmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subchannels',
            name='subchannel_root',
        ),
        migrations.DeleteModel(
            name='ChannelMembership',
        ),
        migrations.DeleteModel(
            name='Subchannels',
        ),
    ]
