# Generated by Django 5.0.3 on 2024-04-21 03:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_channelmembership_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together={('user', 'subchannel_group')},
        ),
    ]
